#-------------------------------------
#  Lab04 - Work this GitHub Actions
#  @Kyala16
#-------------------------------------

name: Formatter

on:
  push:
    branches: 
    - main

  workflow_dispatch:

jobs:
  Build-library:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build formatter_lib
        shell: bash
        run: |
          cd formatter_lib/build
          cmake ..
          cmake -build .
          
      - name: Build formatter_ex_lib
        shell: bash
        run: |
          cd formatter_ex_lib/build
          cmake ..
          cmake -build .

      - name: Build solver_lib
        shell: bash
        run: |
          cd solver_lib/build
          cmake ..
          cmake -build .
